class_names = [
    '1 Explosives',
    '1-1 Explosives Products with the potential to create a mass explosion',
    '1-2 Explosives Products with the potential to create a projectile hazard',
    '1-3 Explosives Products with the potential to create a fire or minor blast',
    '1-4 Explosives Products with no significant risk of creating a blast',
    '1-5 Explosives Products considered very insensitive that are used as blasting agents',
    '1-6 Explosives Products considered extremely insensitive with no risk to create a mass explosion',
    '2 Oxygen',
    '2-1 Flammable gases',
    '2-2 Nonflammable gases',
    '2-3 Toxic gases',
    '3 Combustible',
    '3 Flammable',
    '3 Flammable and combustible liquids',
    '3 Flammable liquid',
    '4-1 Flammable solids',
    '4-2 Spontaneously combustible',
    '4-3 Dangerous when wet',
    '5-1 Oxidizing substances',
    '5-2 Organic peroxides',
    '6 Poisons',
    '7 Radioactive',
    '8 Corrosive',
    '9 Miscellaneous',
    'Dangerous',
    'Environmentally Hazardous Substance',
    'Hot',
    'Infectious Substance',
    'Orange Panel',
    'Placards',
    'Spontaneously combustible material',
    'license plate'
]