class_names = [
    "011_Oxidizer",
    "Combustible",
    "Corrosive",
    "Dangerous",
    "Dangerous when wet",
    "Environmentally Hazardous Substance",
    "Explosives",
    "Explosives Products considered extremely insensitive with no risk to create a mass explosion",
    "Explosives Products considered very insensitive that are used as blasting agents",
    "Explosives Products with no significant risk of creating a blast",
    "Explosives Products with the potential to create a fire or minor blast",
    "Explosives Products with the potential to create a mass explosion",
    "Explosives Products with the potential to create a projectile hazard",
    "Flammable",
    "Flammable and combustible liquids",
    "Flammable gases",
    "Flammable liquid",
    "Flammable solids",
    "Fuel oil",
    "Hot",
    "Infectious Substance",
    "Infectous Substance",
    "Inhalation Hazard",
    "Miscellaneous",
    "Miscellaneous dangerous goods",
    "Nonflammable gases",
    "Orange Panel",
    "Organic Peroxide",
    "Organic peroxides",
    "Oxidizer",
    "Oxidizing substances",
    "Oxygen",
    "Placards",
    "Poison",
    "Poisons",
    "Radioactive",
    "Spontaneously combustible",
    "Spontaneously combustible material",
    "Toxic gases",
    "combustible",
    "dangerous",
    "explosive substances",
    "hazardous voltage",
    "heated materials",
    "license plate",
    "organic peroxids",
    "oxidising agents",
    "subsidiary risk label",
    "toxins"
]