class_names = [
    "Combustible",
    "Corrosive",
    "Dangerous",
    "Dangerous Wet",
    "Env Hazardous",
    "Explosives",
    "Explosives No Mass Risk",
    "Explosives Blasting",
    "Explosives Low Risk",
    "Explosives Minor Blast",
    "Explosives Mass Explosion",
    "Explosives Projectile Hazard",
    "Flammable",
    "Flammable Liquid Combustible",
    "Flammable Gases",
    "Flammable Liquid",
    "Flammable Solids",
    "Fuel Oil",
    "Hot",
    "Infectious",
    "Miscellaneous",
    "Nonflammable Gases",
    "Orange Panel",
    "Organic Peroxide",
    "Oxidizer",
    "Oxidizing",
    "Oxygen",
    "Placards",
    "Poison",
    "Radioactive",
    "Spont Combustible",
    "Toxic Gases",
    "License Plate"
]
